### ISSUE TITLE
[SHB] Check setup compatibility

### ISSUE THREAD

**Issue by Al-Andrew** [Al-Andrew/SmartHouse-Builder#210]
We should have way to check if all the items in a setup are compatible with each other and highlight the ones that don't correspond with an error message.

I propose we make a backend route for this purpose at `/api/shb/compat`  but it can be done on the front end as well.

**Comment by EnascutaRazvan** [comment]
I ll take care about this issue

**Comment by horiaapostol** [comment]
+ help
