### ISSUE TITLE
Product scraping

### ISSUE THREAD

**Issue by Al-Andrew** [Al-Andrew/SmartHouse-Builder#33]
Scrape the internet ( or a few whitelisted sites ) for smart devices and their specification sheets

**Comment by EnascutaRazvan** [comment]
Voi rezolva eu la acest issue

**Comment by Al-Andrew** [comment]
For sprint 2 we should focus on getting the product information as well as the sizes of the products.

**Comment by Al-Andrew** [comment]
This issue is being closed and broken down into multiple issues.
