### ISSUE TITLE
Home Layout floor view

### ISSUE THREAD

**Issue by Al-Andrew** [Al-Andrew/SmartHouse-Builder#53]
We should make a basic floor editor. including just the walls and wall embed-able non-smart objects, ie. window, door, outlet. The editor should support:
- Creating walls/windows/doors/outlets
- Moving and sizing them
- Snapping (maybe? stretch)

**Comment by ndrey12** [comment]
.

**Comment by Al-Andrew** [comment]
see pr #56 and fix delayed rendering

**Comment by Al-Andrew** [comment]
This issue has been closed and broken into several smaller issues.
